name: "Build custom branches"

on:
   push:
      branches:
         - '*'

concurrency:
   group: ${{ github.ref }}
   cancel-in-progress: true


jobs:
   MavenDeploy:
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout
            uses: actions/checkout@v3

         -  uses: actions/setup-java@v3
            with:
               distribution: 'adopt'
               java-version: '17'

         -  name: Cache local Maven repository
            uses: actions/cache@v3
            with:
               path: ~/.m2/repository
               key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
               restore-keys: |
                  ${{ runner.os }}-maven-

         -  uses: s4u/maven-settings-action@v2.3.0
            with:
               servers: |
                  [{
                      "id": "ossrh",
                      "username": "${{ secrets.OSS_NAME }}",
                      "password": "${{ secrets.OSS_PASS }}"
                  },
                  {
                      "id": "oss-snapshot",
                      "username": "${{ secrets.OSS_NAME }}",
                      "password": "${{ secrets.OSS_PASS }}"
                  }]

         -  name: mvn deploy
            run: |
               (echo "===== Maven Deploy Attempt: 1 ====" >> $GITHUB_STEP_SUMMARY && _custom/bin/mvn-deploy.sh) || \
               (sleep 120 && echo "===== Maven Deploy Attempt: 2 ====" >> $GITHUB_STEP_SUMMARY && _custom/bin/mvn-deploy.sh) || \
               (sleep 120 && echo "===== Maven Deploy Attempt: 3 ====" >> $GITHUB_STEP_SUMMARY && _custom/bin/mvn-deploy.sh) || \
               (echo "==== Maven Deploy Step Failed ====" >> $GITHUB_STEP_SUMMARY && exit 1)
